config/routes.rb
Rails.application.routes.draw do
	root 'messages#index'
	
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	get 'logout', to: 'sessions#delete'
	
	get '/signup', to: 'users#new'
	resources :users, only: [:index, :show, :create]
	resources :messages
	resources :friendships
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, :class_name => 'User'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
	mount_uploader :image, MessimageUploader
end

app/models/user.rb
class User < ApplicationRecord
	has_many :messages, dependent: :destroy
	has_many :friendships
 	has_many :friends, :through => :friendships
  validates :name, presence: true
	validates :email, presence: true
	validates :password, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	def authenticate
		if session[:current_user].nil?
			redirect_to login_path
		end
	end

	def current_user
		return unless session[:current_user]
		@current_user ||= session[:current_user]
	end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

	def create
		user = User.find(current_user["id"])
		@friendship = user.friendships.create(user_id: user.id, friend_id: params[:friend_id])

		if @friendship 
			flash[:success] = "Added #{@friendship.friend.name} as a new friend."
			redirect_to users_path
		else
			flash[:error] = "Unable to add user #{@friendship.friend.name}."
			redirect_to messages_path
		end

	end

	def destroy
		@friendship = Friendship.find(params[:id])
		@friendship.destroy
		redirect_to user_path(current_user["id"]) 
	end

	private
	def friendship_params
		params.require(:friendship).permit(:user_id, :friend_id)
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate
	def index
		filter_send = params[:send]

		if filter_send.nil?
			#filter_send = null => receiver = current_user 
			@messages = Message.where("receiver = #{current_user["id"]}").order("created_at DESC")
		else
			@messages = Message.where("user_id = #{current_user["id"]}").order("created_at DESC")
		end
	end

	def show
		@message = Message.find(params[:id])

		if !@message.isread
			Time.zone = 'Hanoi'
			@message.update_attribute(:time_read, Time.current)
			@message.update_attribute(:isread, true)
		end
	end

	def new
		@message = Message.new
		@friends = User.where(id: Friendship.where("user_id = #{current_user["id"]}").pluck(:friend_id))
	end

	def create
		current_user = User.find(session[:current_user]["id"])	
		@message = current_user.messages.new(message_params)
		if @message.save
			flash[:success] = "Sent message to #{User.find(@message.receiver).name}."
			redirect_to messages_path
		else
			flash[:error] = "Cannot send message."
			render 'new'
		end

	end
	
	private
		def message_params
			params.require(:message).permit(:receiver, :text, :image)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(session_params)

		if user.nil?
			flash[:error] = "Wrong email or password."
			render 'new'
		else
			session[:current_user] = user
			flash[:success] = "Login successfully."
			redirect_to messages_path 
		end
	end

	def delete
		session.delete(:current_user)
		redirect_to login_path
	end

	private
		def session_params
			params.require(:session).permit(:email, :password)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def new
	end

	def index
		@users = User.where.not(id: Friendship.where("user_id = #{current_user["id"]}").pluck(:friend_id)).where.not(id: current_user["id"])
	end


	def show
		@user = User.find(current_user["id"])
	end

	def create
		user = User.create(user_params)

		if user
			flash[:success] = "Register successfully."
			redirect_to messages_path 
		else
			flash[:error] = "Cannot create new account."
			render 'new'
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/send_messages_helper.rb
module SendMessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="/">
		<img src="" width="30" height="30" alt="">
	</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMobile" aria-controls="navbarMobile" aria-expanded="false" aria-label="Toggle navigation" >
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarMobile">
		<ul class="nav mr-auto text-center">
			<li class="nav-item active"><a class="nav-link" href="/">Home <span class="sr-only"></span></a></li>
			<li class="nav-item"><a class="nav-link" href="/">Message</a></li>
			</li>
			<li class="nav-item"><a class="nav-link" href="/">About</a></li>
		</ul>

		<ul class="nav ml-auto">
			<% if session[:current_user] %>
				<li class="nav-item"><a class="nav-link"><%= session[:current_user]["id"] %></a></li>
				<li class="nav-item"><a class="nav-link"><%= session[:current_user]["name"] %></a></li>
				<li class="nav-item">
				<%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %>
			</li>
		<% else %>
				<li class="nav-item">
			<%= link_to "Login", login_path, class: "nav-link" %>
			</li>
		<% end %>
		</ul>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Simple Chat Application</title>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= csrf_meta_tags %>
	</head>

	<body>
		<%= render "layouts/navbar" %>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<%= yield %>
				</div>
			</div>
		</div>
	</body>
</html>

app/views/messages/_show_messages.html.erb
<% @messages.each do |message| %>
	<div class="col-md-4 pb-3">
		<% if message.isread %>
		<div class="card bg-info text-white">
		<% else %> 
		<div class="card bg-warning text-white">
		<% end %>
		<div class="card-body">
			<% if params[:send] %>
				<h5 class="card-title">To: <%= User.find(message.receiver).name %></h5>
			<% else %>
				<h5 class="card-title">From: <%= message.user.name %></h5>
			<% end %>
				<p class="card-text"><%= truncate(message.text, :length=> 100) %></p>
				<%= link_to "Show", message_path(message), :class => "btn btn-primary" %>
			</div>
	</div>
</div>
<% end %>	

app/views/messages/index.html.erb
<div class="container">
	<% if flash[:success] != nil %>
	<div class="row">
		<div class="col-md-12 pt-3 pb-3">
			<div class="alert alert-success alert-dismissible fade show" role="alert">
				<%= flash[:success] %>
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		</div>
	</div>
	<% end %>
	<div class="row">
		<div class="col-md-12 pt-3 pb-3 text-center">
			<i><%= link_to 'Compose', new_message_path, :class => "btn btn-success" %></i>
			<%= link_to 'Sent Message', messages_path(:send => 1), :class => "btn btn-info" %>
			<%= link_to 'Received Message', messages_path, :class => "btn btn-info" %>
			<%= link_to 'Friend List', user_path(@current_user["id"]), :class => "btn btn-info" %>
			<%= link_to 'User List', users_path, :class => "btn btn-info" %>

			<% if params[:send] %>
				<h3 class="text-center pt-3">Sent Messages</h3>
			<% else %>
				<h3 class="text-center pt-3">Received Messages</h3>
			<% end %>

		</div>
		<%= render 'show_messages' %>
	</div>
</div>

app/views/messages/new.html.erb
<div class="container">
	<div class="row">
		<h1 class="col-md-12 text-center">New Message</h1>

		<div class="col-md-3 pb-3">
			<%= link_to '<< Back', messages_path, :class => "btn btn-secondary" %>
		</div>

		<div class="col-md-12">
			<%= form_with model: @message, url: messages_path, local: true, :html => {:multipart => true} do |form| %>

			<div class="form-group">
				<%= form.label :Receiver %><br>
				<%= form.collection_select :receiver, @friends , :id, :name, {require: true}, :class => "form-control" %>
			</div>

			<div class="form-group">
				<%= form.label :Text %><br>
				<%= form.text_area :text, :class => "form-control" %>
			</div>

			<div class="form-group">
				<label for="">Image</label>
				<%= form.file_field :image, :class => "form-control" %>
			</div>
			<input class="btn btn-primary" type="submit" value="Send">
		<% end %>
		</div>
	</div>
</div>

app/views/messages/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<form>
				<% if @message.user_id == session[:current_user]["id"] %>
					<div class="form-group">
						<label>To</label>
						<input class="form-control" type="text" placeholder="<%= User.find(@message.receiver).name %>" readonly>
					</div>
					<div class="form-group">
						<label>Content</label>
						<textarea class="form-control" readonly><%= @message.text %></textarea>
					</div>
					<div class="form-group">
						<label>Sent Time</label>
						<input class="form-control" type="text" placeholder="<%= @message.created_at.strftime('%H:%M:%S %d-%m-%Y') %>" readonly>
					</div>
				<%= image_tag @message.image.url unless @message.image.blank? %>
				<% else %>
					<div class="form-group">
						<label>From</label>
						<input class="form-control" type="text" placeholder="<%= @message.user.name %>" readonly>
					</div>
					<div class="form-group">
						<label>Content</label>
						<textarea class="form-control" readonly><%= @message.text %></textarea>
					</div>
					<div class="form-group">
						<label>Read Time</label>
						<input class="form-control" type="text" placeholder="<%= @message.time_read.strftime('%H:%M:%S %d-%m-%Y') %>" readonly>
					</div>
				<%= image_tag @message.image.url unless @message.image.blank? %>
				<% end %>
			</form>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<% if flash[:success] != nil %>
	<div class="row">
		<div class="col-md-12 pb-3 pt-3">
			<div class="alert alert-success alert-dismissible fade show" role="alert">
				<%= flash[:success] %>
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		</div>
	</div>
	<% end %>
	<div class="row">
		<div class="col-md-12 pb-3">
			<h1 class="text-center text-info pt-1 pb-3">USER LIST</h1>
			<div class="row">
				<% @users.each do |user| %>
					<div class="col-md-4 text-center">
						<strong><%= user.name %></strong>
						<%= button_to "Add Friend", friendships_path(:friend_id => user), :form_class => "pt-1", :class => "btn btn-primary" %> 
					</div>
				<% end %>	
			</div>
			
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div class="row">
	<h1>Register Page</h1>
</div>

<div class="row">
	<div class="col-md-12">
		<%= form_with scope: :user, url: users_path, local: true do |f|%>
			<div class="form-group">
			<label for="">Name</label> 
			<%= f.text_field :name, class: "form-control" %>
		</div>

		<div class="form-group">
			<label for="">Email</label> 
			<%= f.text_field :email, class: "form-control" %>
		</div>

		<div class="form-group">
			<label for="">Password</label>
			<%= f.password_field :password, class: "form-control" %>
		</div>

		<button type="submit" class="btn btn-primary">Register</button>
	<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="text-center text-info pt-1 pb-3">FRIEND LIST</h1>
			<div class="row">
				<% for friendship in @user.friendships %>
					<div class="col-md-4 text-center">
						<%= friendship.friend.name %>
						<%= button_to "Remove", friendship_path(friendship), method: :delete, :class => "btn btn-danger" %>
					</div>
				<% end %>	
			</div>
		</div>
	</div>
</div>